//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JigneshWebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;   
    public partial class Admin
    {
        public int AdminId { get; set; }
        [Required]
        [Display(Name = "Enter UserName")]

    
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
        [Required]

        public string Email { get; set; }
        [Required]
        public string Phone { get; set; }
    }
}
