//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JigneshWebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Car_Sell_Detail
    {
        public int CarSellDetailId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        [Required]
        [Display(Name = "Enter CarName")]
        public string CarName { get; set; }
        [Required]
        public string CarModel { get; set; }

        [Required(ErrorMessage = "enter valid price.")]
        [RegularExpression(@"^\d*$",
                      ErrorMessage = "Price is not valid")]
        public Nullable<decimal> Price { get; set; }
        [Required]
        public string ShortDescription { get; set; }
        [Required]
        public string LongDescription { get; set; }

        [Required]
        public string ImageName { get; set; }
    }
}
